/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRfqsRouteImport } from './routes/_authenticated/rfqs'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMarketplaceFavouritesRouteImport } from './routes/_authenticated/marketplace.favourites'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicV1RfqsRouteImport } from './routes/api/public/v1/rfqs'
import { Route as ApiPublicV1RestockRouteImport } from './routes/api/public/v1/restock'
import { Route as ApiPublicV1QuotationsRouteImport } from './routes/api/public/v1/quotations'
import { Route as ApiPublicV1PurchaseOrdersRouteImport } from './routes/api/public/v1/purchase-orders'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1InventoryRouteImport } from './routes/api/public/v1/inventory'
import { Route as ApiPublicV1ConnectionsRouteImport } from './routes/api/public/v1/connections'
import { Route as ApiPublicV1CompaniesRouteImport } from './routes/api/public/v1/companies'
import { Route as AuthenticatedMarketplaceSupplierIdRouteImport } from './routes/_authenticated/marketplace.supplier.$id'
import { Route as AuthenticatedMarketplaceProductIdRouteImport } from './routes/_authenticated/marketplace.product.$id'
import { Route as ApiPublicV1DeliveriesIdRouteImport } from './routes/api/public/v1/deliveries.$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfqsRoute = AuthenticatedRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketplaceFavouritesRoute =
  AuthenticatedMarketplaceFavouritesRouteImport.update({
    id: '/favourites',
    path: '/favourites',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RfqsRoute = ApiPublicV1RfqsRouteImport.update({
  id: '/api/public/v1/rfqs',
  path: '/api/public/v1/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RestockRoute = ApiPublicV1RestockRouteImport.update({
  id: '/api/public/v1/restock',
  path: '/api/public/v1/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuotationsRoute = ApiPublicV1QuotationsRouteImport.update({
  id: '/api/public/v1/quotations',
  path: '/api/public/v1/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PurchaseOrdersRoute =
  ApiPublicV1PurchaseOrdersRouteImport.update({
    id: '/api/public/v1/purchase-orders',
    path: '/api/public/v1/purchase-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InventoryRoute = ApiPublicV1InventoryRouteImport.update({
  id: '/api/public/v1/inventory',
  path: '/api/public/v1/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ConnectionsRoute = ApiPublicV1ConnectionsRouteImport.update({
  id: '/api/public/v1/connections',
  path: '/api/public/v1/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CompaniesRoute = ApiPublicV1CompaniesRouteImport.update({
  id: '/api/public/v1/companies',
  path: '/api/public/v1/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketplaceSupplierIdRoute =
  AuthenticatedMarketplaceSupplierIdRouteImport.update({
    id: '/supplier/$id',
    path: '/supplier/$id',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceProductIdRoute =
  AuthenticatedMarketplaceProductIdRouteImport.update({
    id: '/product/$id',
    path: '/product/$id',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const ApiPublicV1DeliveriesIdRoute = ApiPublicV1DeliveriesIdRouteImport.update({
  id: '/api/public/v1/deliveries/$id',
  path: '/api/public/v1/deliveries/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfqs': typeof AuthenticatedRfqsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/marketplace/favourites': typeof AuthenticatedMarketplaceFavouritesRoute
  '/marketplace/product/$id': typeof AuthenticatedMarketplaceProductIdRoute
  '/marketplace/supplier/$id': typeof AuthenticatedMarketplaceSupplierIdRoute
  '/api/public/v1/companies': typeof ApiPublicV1CompaniesRoute
  '/api/public/v1/connections': typeof ApiPublicV1ConnectionsRoute
  '/api/public/v1/inventory': typeof ApiPublicV1InventoryRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
  '/api/public/v1/purchase-orders': typeof ApiPublicV1PurchaseOrdersRoute
  '/api/public/v1/quotations': typeof ApiPublicV1QuotationsRoute
  '/api/public/v1/restock': typeof ApiPublicV1RestockRoute
  '/api/public/v1/rfqs': typeof ApiPublicV1RfqsRoute
  '/api/public/v1/deliveries/$id': typeof ApiPublicV1DeliveriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfqs': typeof AuthenticatedRfqsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/marketplace/favourites': typeof AuthenticatedMarketplaceFavouritesRoute
  '/marketplace/product/$id': typeof AuthenticatedMarketplaceProductIdRoute
  '/marketplace/supplier/$id': typeof AuthenticatedMarketplaceSupplierIdRoute
  '/api/public/v1/companies': typeof ApiPublicV1CompaniesRoute
  '/api/public/v1/connections': typeof ApiPublicV1ConnectionsRoute
  '/api/public/v1/inventory': typeof ApiPublicV1InventoryRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
  '/api/public/v1/purchase-orders': typeof ApiPublicV1PurchaseOrdersRoute
  '/api/public/v1/quotations': typeof ApiPublicV1QuotationsRoute
  '/api/public/v1/restock': typeof ApiPublicV1RestockRoute
  '/api/public/v1/rfqs': typeof ApiPublicV1RfqsRoute
  '/api/public/v1/deliveries/$id': typeof ApiPublicV1DeliveriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rfqs': typeof AuthenticatedRfqsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/marketplace/favourites': typeof AuthenticatedMarketplaceFavouritesRoute
  '/_authenticated/marketplace/product/$id': typeof AuthenticatedMarketplaceProductIdRoute
  '/_authenticated/marketplace/supplier/$id': typeof AuthenticatedMarketplaceSupplierIdRoute
  '/api/public/v1/companies': typeof ApiPublicV1CompaniesRoute
  '/api/public/v1/connections': typeof ApiPublicV1ConnectionsRoute
  '/api/public/v1/inventory': typeof ApiPublicV1InventoryRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRoute
  '/api/public/v1/purchase-orders': typeof ApiPublicV1PurchaseOrdersRoute
  '/api/public/v1/quotations': typeof ApiPublicV1QuotationsRoute
  '/api/public/v1/restock': typeof ApiPublicV1RestockRoute
  '/api/public/v1/rfqs': typeof ApiPublicV1RfqsRoute
  '/api/public/v1/deliveries/$id': typeof ApiPublicV1DeliveriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api-keys'
    | '/catalog'
    | '/dashboard'
    | '/deliveries'
    | '/inventory'
    | '/invitations'
    | '/marketplace'
    | '/network'
    | '/onboarding'
    | '/organization'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/settings'
    | '/suppliers'
    | '/warehouses'
    | '/.mcp/invoke-tool/$tool'
    | '/marketplace/favourites'
    | '/marketplace/product/$id'
    | '/marketplace/supplier/$id'
    | '/api/public/v1/companies'
    | '/api/public/v1/connections'
    | '/api/public/v1/inventory'
    | '/api/public/v1/products'
    | '/api/public/v1/purchase-orders'
    | '/api/public/v1/quotations'
    | '/api/public/v1/restock'
    | '/api/public/v1/rfqs'
    | '/api/public/v1/deliveries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api-keys'
    | '/catalog'
    | '/dashboard'
    | '/deliveries'
    | '/inventory'
    | '/invitations'
    | '/marketplace'
    | '/network'
    | '/onboarding'
    | '/organization'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/settings'
    | '/suppliers'
    | '/warehouses'
    | '/.mcp/invoke-tool/$tool'
    | '/marketplace/favourites'
    | '/marketplace/product/$id'
    | '/marketplace/supplier/$id'
    | '/api/public/v1/companies'
    | '/api/public/v1/connections'
    | '/api/public/v1/inventory'
    | '/api/public/v1/products'
    | '/api/public/v1/purchase-orders'
    | '/api/public/v1/quotations'
    | '/api/public/v1/restock'
    | '/api/public/v1/rfqs'
    | '/api/public/v1/deliveries/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/api-keys'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/inventory'
    | '/_authenticated/invitations'
    | '/_authenticated/marketplace'
    | '/_authenticated/network'
    | '/_authenticated/onboarding'
    | '/_authenticated/organization'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/quotations'
    | '/_authenticated/reports'
    | '/_authenticated/rfqs'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/warehouses'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/marketplace/favourites'
    | '/_authenticated/marketplace/product/$id'
    | '/_authenticated/marketplace/supplier/$id'
    | '/api/public/v1/companies'
    | '/api/public/v1/connections'
    | '/api/public/v1/inventory'
    | '/api/public/v1/products'
    | '/api/public/v1/purchase-orders'
    | '/api/public/v1/quotations'
    | '/api/public/v1/restock'
    | '/api/public/v1/rfqs'
    | '/api/public/v1/deliveries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicV1CompaniesRoute: typeof ApiPublicV1CompaniesRoute
  ApiPublicV1ConnectionsRoute: typeof ApiPublicV1ConnectionsRoute
  ApiPublicV1InventoryRoute: typeof ApiPublicV1InventoryRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRoute
  ApiPublicV1PurchaseOrdersRoute: typeof ApiPublicV1PurchaseOrdersRoute
  ApiPublicV1QuotationsRoute: typeof ApiPublicV1QuotationsRoute
  ApiPublicV1RestockRoute: typeof ApiPublicV1RestockRoute
  ApiPublicV1RfqsRoute: typeof ApiPublicV1RfqsRoute
  ApiPublicV1DeliveriesIdRoute: typeof ApiPublicV1DeliveriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs': {
      id: '/_authenticated/rfqs'
      path: '/rfqs'
      fullPath: '/rfqs'
      preLoaderRoute: typeof AuthenticatedRfqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/favourites': {
      id: '/_authenticated/marketplace/favourites'
      path: '/favourites'
      fullPath: '/marketplace/favourites'
      preLoaderRoute: typeof AuthenticatedMarketplaceFavouritesRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/rfqs': {
      id: '/api/public/v1/rfqs'
      path: '/api/public/v1/rfqs'
      fullPath: '/api/public/v1/rfqs'
      preLoaderRoute: typeof ApiPublicV1RfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/restock': {
      id: '/api/public/v1/restock'
      path: '/api/public/v1/restock'
      fullPath: '/api/public/v1/restock'
      preLoaderRoute: typeof ApiPublicV1RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quotations': {
      id: '/api/public/v1/quotations'
      path: '/api/public/v1/quotations'
      fullPath: '/api/public/v1/quotations'
      preLoaderRoute: typeof ApiPublicV1QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/purchase-orders': {
      id: '/api/public/v1/purchase-orders'
      path: '/api/public/v1/purchase-orders'
      fullPath: '/api/public/v1/purchase-orders'
      preLoaderRoute: typeof ApiPublicV1PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory': {
      id: '/api/public/v1/inventory'
      path: '/api/public/v1/inventory'
      fullPath: '/api/public/v1/inventory'
      preLoaderRoute: typeof ApiPublicV1InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/connections': {
      id: '/api/public/v1/connections'
      path: '/api/public/v1/connections'
      fullPath: '/api/public/v1/connections'
      preLoaderRoute: typeof ApiPublicV1ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/companies': {
      id: '/api/public/v1/companies'
      path: '/api/public/v1/companies'
      fullPath: '/api/public/v1/companies'
      preLoaderRoute: typeof ApiPublicV1CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/supplier/$id': {
      id: '/_authenticated/marketplace/supplier/$id'
      path: '/supplier/$id'
      fullPath: '/marketplace/supplier/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceSupplierIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/product/$id': {
      id: '/_authenticated/marketplace/product/$id'
      path: '/product/$id'
      fullPath: '/marketplace/product/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceProductIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/api/public/v1/deliveries/$id': {
      id: '/api/public/v1/deliveries/$id'
      path: '/api/public/v1/deliveries/$id'
      fullPath: '/api/public/v1/deliveries/$id'
      preLoaderRoute: typeof ApiPublicV1DeliveriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceFavouritesRoute: typeof AuthenticatedMarketplaceFavouritesRoute
  AuthenticatedMarketplaceProductIdRoute: typeof AuthenticatedMarketplaceProductIdRoute
  AuthenticatedMarketplaceSupplierIdRoute: typeof AuthenticatedMarketplaceSupplierIdRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceFavouritesRoute:
      AuthenticatedMarketplaceFavouritesRoute,
    AuthenticatedMarketplaceProductIdRoute:
      AuthenticatedMarketplaceProductIdRoute,
    AuthenticatedMarketplaceSupplierIdRoute:
      AuthenticatedMarketplaceSupplierIdRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRfqsRoute: typeof AuthenticatedRfqsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRfqsRoute: AuthenticatedRfqsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicV1CompaniesRoute: ApiPublicV1CompaniesRoute,
  ApiPublicV1ConnectionsRoute: ApiPublicV1ConnectionsRoute,
  ApiPublicV1InventoryRoute: ApiPublicV1InventoryRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRoute,
  ApiPublicV1PurchaseOrdersRoute: ApiPublicV1PurchaseOrdersRoute,
  ApiPublicV1QuotationsRoute: ApiPublicV1QuotationsRoute,
  ApiPublicV1RestockRoute: ApiPublicV1RestockRoute,
  ApiPublicV1RfqsRoute: ApiPublicV1RfqsRoute,
  ApiPublicV1DeliveriesIdRoute: ApiPublicV1DeliveriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
